Adds a "Struct Sequence" type:
This type allows one to specify records using textual names and
the same datasyntax as used in Python's "struct" model.

It them allows one to create and access records on the specified fields
keeping all record data in a single sequence in memory (a Python bytearray object).

It should be a rather compact solution to manipulate millions of records with
numeric fields.
(Currrently it uses the raw "struct" module to serialize/deserialize data,
thus text support is rather poor, being limited to fixed lenght
bytes objects)

>>> from structsequence import StructSequence
>>> points = StructSequence("points", "x y", "hh")
>>> points.append((0,0))
>>> points[0]
<points object[0]: {'x':0, 'y':0}>
>>> points[0].x = 20000
>>> points[0]
<points object[0]: {'x':20000, 'y':0}>
>>> points[0].y = 33000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
struct.error: short format requires (-0x7fff - 1) <= number <= 0x7fff